# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191110_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='/1.jpg', upload_to=''),
        ),
    ]
