# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191112_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(upload_to='head'),
        ),
    ]
